# Generated by Django 2.0.5 on 2018-09-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusnessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=25, null=True)),
                ('opentime', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.TextField()),
                ('logoimg', models.CharField(blank=True, max_length=100, null=True)),
                ('wximg', models.CharField(blank=True, max_length=100, null=True)),
                ('busimg', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusnessTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='busnessinfo',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busness_info', to='busness.BusnessTag'),
        ),
        migrations.AddField(
            model_name='busnessinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busness', to=settings.AUTH_USER_MODEL),
        ),
    ]
