# Generated by Django 2.0.5 on 2018-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20180906_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
