# Generated by Django 2.0.5 on 2018-08-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20180812_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
