# Generated by Django 2.0.5 on 2018-08-13 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechat', '0006_auto_20180812_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=20)),
                ('position', models.CharField(default=None, max_length=50)),
                ('housetype', models.CharField(default=None, max_length=50)),
                ('area', models.CharField(default=None, max_length=20)),
                ('price', models.CharField(default=None, max_length=20)),
                ('detail', models.TextField()),
                ('img', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='house_trade',
            name='tag',
            field=models.ManyToManyField(related_name='house', to='wechat.HouseTag'),
        ),
        migrations.AddField(
            model_name='house_trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housemsg', to=settings.AUTH_USER_MODEL),
        ),
    ]
