# Generated by Django 2.0.5 on 2018-08-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20180813_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('house', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_total', to='wechat.House_Trade')),
                ('job', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_total', to='wechat.JobInfo')),
            ],
        ),
    ]
