# Generated by Django 2.0.5 on 2018-08-13 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
