# Generated by Django 2.0.5 on 2018-08-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_auto_20180813_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='house',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_total', to='wechat.House_Trade'),
        ),
        migrations.AlterField(
            model_name='total',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_total', to='wechat.JobInfo'),
        ),
    ]
