# Generated by Django 2.0.5 on 2018-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0016_auto_20180820_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
