# Generated by Django 2.0.5 on 2018-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0017_auto_20180820_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='requre',
            field=models.ManyToManyField(blank=True, related_name='jobtag', to='wechat.JobTag'),
        ),
    ]
