# Generated by Django 2.0.5 on 2018-08-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechat', '0018_auto_20180820_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('beginning', models.CharField(blank=True, max_length=30)),
                ('destination', models.CharField(blank=True, max_length=30)),
                ('begin_time', models.CharField(blank=True, max_length=20)),
                ('seat', models.CharField(blank=True, max_length=10, null=True)),
                ('isfee', models.CharField(blank=True, max_length=10)),
                ('detail', models.TextField()),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarpoolTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emehelp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('detail', models.TextField()),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifeservice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookForHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookhelp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('carsystem', models.CharField(blank=True, max_length=20)),
                ('carmodel', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('car_age', models.CharField(blank=True, max_length=20)),
                ('distance', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField()),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldcar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olditem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='house_trade',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='type',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='carpool',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='carpool', to='wechat.CarpoolTag'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool', to=settings.AUTH_USER_MODEL),
        ),
    ]
