# Generated by Django 2.0.5 on 2018-08-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0019_auto_20180821_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyhelp',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lifeservice',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lookforhelp',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oldcar',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='olditem',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='total',
            name='car_pool',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_pool', to='wechat.CarPool'),
        ),
        migrations.AddField(
            model_name='total',
            name='eme_help',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eme_help', to='wechat.EmergencyHelp'),
        ),
        migrations.AddField(
            model_name='total',
            name='life_ser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_service', to='wechat.LifeService'),
        ),
        migrations.AddField(
            model_name='total',
            name='look_help',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='look_help', to='wechat.LookForHelp'),
        ),
        migrations.AddField(
            model_name='total',
            name='old_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_car', to='wechat.OldCar'),
        ),
        migrations.AddField(
            model_name='total',
            name='old_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_item', to='wechat.OldItem'),
        ),
    ]
