# Generated by Django 2.0.5 on 2018-08-22 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0022_auto_20180821_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='belong_articel',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='belong_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='belong_article',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='wechat.Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='belong_article',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='wechat.Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='belong_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='belong_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repy_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
