# Generated by Django 2.0.5 on 2018-08-22 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0023_auto_20180822_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='belong_article',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='wechat.Total'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reply',
            name='belong_article',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='wechat.Total'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
