# Generated by Django 2.0.5 on 2018-08-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0024_auto_20180822_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='belong_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='wechat.Total'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='belong_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='wechat.Total'),
        ),
    ]
