# Generated by Django 2.0.5 on 2018-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0025_auto_20180822_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='width_field',
        ),
        migrations.AddField(
            model_name='images',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carpool',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='house_trade',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='img',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lifeservice',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
