# Generated by Django 2.0.5 on 2018-08-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0026_auto_20180827_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookforhelp',
            name='img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
