# Generated by Django 2.0.5 on 2018-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0027_auto_20180830_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lookforhelp',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
