# Generated by Django 2.0.5 on 2018-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0028_auto_20180830_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyhelp',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house_trade',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lifeservice',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oldcar',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='olditem',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
