# Generated by Django 2.0.5 on 2018-09-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0029_auto_20180831_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.JobInfo'),
        ),
    ]
