# Generated by Django 2.0.5 on 2018-09-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0030_auto_20180901_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='car_pool',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.CarPool'),
        ),
    ]
