# Generated by Django 2.0.5 on 2018-09-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0031_auto_20180901_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='eme_help',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.EmergencyHelp'),
        ),
        migrations.AlterField(
            model_name='total',
            name='house',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.House_Trade'),
        ),
        migrations.AlterField(
            model_name='total',
            name='life_ser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.LifeService'),
        ),
        migrations.AlterField(
            model_name='total',
            name='look_help',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.LookForHelp'),
        ),
        migrations.AlterField(
            model_name='total',
            name='old_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.OldCar'),
        ),
        migrations.AlterField(
            model_name='total',
            name='old_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.OldItem'),
        ),
    ]
